name: permission_request_page
description: A widget that explains and requests why app permissions are needed.
version: 1.0.0
homepage: https://github.com/Dev-hwang/permission_request_page

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  animations: 
  permission_handler: 
  shared_preferences: 
  device_info_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.pravera.permission_request_page
        pluginClass: PermissionRequestPagePlugin
      ios:
        pluginClass: PermissionRequestPagePlugin
